### ISSUE TITLE
source/html time error

### ISSUE THREAD

**Issue by Cadaei-Yuvxvs** [workflowr/workflowr#198]
I'm having trouble running the `wflow_publish` function. It gives me this error when I run it:
```
Error in if (recent_source_time >= recent_html_time) { : 
  argument is of length zero
```
I couldn't find a related issue and I'm not sure how I might be able to fix this. Any help would be appreciated.
I'm using workflowr v 1.6.1

**Comment by jdblischak** [comment]
@Cadaei-Yuvxvs Thanks for the bug report. Could you please try disabling the use of the system Git executable and then re-run `wflow_publish()`?

```
options(workflowr.sysgit = "")
```

And here are some other diagnostics that may be useful to troubleshoot this issue. Please run these in the R console and copy-paste their output here:

1. `sessionInfo()`
1. `Sys.which("git")`

**Comment by Cadaei-Yuvxvs** [comment]
Thank you for your prompt reply. The error still persists after disabling the system git executable.

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.6.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4      rprojroot_1.3-2 digest_0.6.25   later_1.0.0     R6_2.4.1        backports_1.1.5 git2r_0.26.1    magrittr_1.5   
 [9] evaluate_0.14   stringi_1.4.6   rlang_0.4.5     rstudioapi_0.11 fs_1.4.0        promises_1.1.0  rmarkdown_2.1   tools_3.6.2    
[17] stringr_1.4.0   yaml_2.2.1      httpuv_1.5.2    xfun_0.12       compiler_3.6.2  htmltools_0.4.0 knitr_1.28     
> Sys.which("git")
                              git 
"C:\\PROGRA~1\\Git\\cmd\\git.exe" 
```

**Comment by jdblischak** [comment]
OK, so that means the error doesn't appear to be caused by Git or git2r. And your setup looks good.

Some more questions:

1. Is your project public? If you can point me to it, I can investigate it myself as well.
1. Could you please copy-paste the exact `wflow_publish()` you enter into the R console and all the output?
1. Did you customize your workflowr project at all? For example, did you make any changes in `_workflowr.yml` or `analysis/_site.yml`?

**Comment by Cadaei-Yuvxvs** [comment]
My project can be found here: https://github.com/Cadaei-Yuvxvs/snrnaseq
This is my first time making a repository, so I apologise if I made any obvious errors.

Here's the input and all the output from the R console:

```
> wflow_publish(message="Follow Up")
Error in if (recent_source_time >= recent_html_time) { : 
  argument is of length zero
> 
```
I may have modified _workflowr.yml, though I don't remember:
```
# workflowr options
# Version 1.5.0

# The seed to use for random number generation. See ?set.seed for details.
seed: 20191218
# The working directory to build the R Markdown files. The path is relative to
# _workflowr.yml. See ?rmarkdown::render for details.
knit_root_dir: "."

```

And I've certainly modified _site.yml:
```
name: snrnaseq
output_dir: ../docs
navbar:
  title: MND snRNA-seq
  left:
  - text: Home
    href: index.html
  - text: Initial Analysis
    href: analysis.html
  - text: C10
    href: follow_up.html
  - text: C19
    href: C19_follow_up.html
  - text: M17
    href: M17_follow_up.html
  - text: M20
    href: M20_follow_up.html
  - text: Controls
    href: Controls_follow_up.html
  - text: Integrated
    href: C19M_follow_up.html
  - text: About
    href: about.html
  - text: License
    href: license.html
  right:
  - icon: fa-github
    text: Source code
    href: https://github.com/Cadaei-Yuvxvs/snrnaseq
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
```
