### ISSUE TITLE
Setting a theme doesn't seem to work

### ISSUE THREAD

**Issue by lukeholman** [workflowr/workflowr#206]
Hi there,

Thanks for a great package! I was just trying to change the default cosmo theme as described in the documentation, and it's apparently not working as expected.

I tried changing the name of theme to several different ones (yeti, darkly, lumen, etc) in `analysis/_site.yml`, and got nowhere, though according to the docs that is all I need to do. I then tried adding e.g. theme: darkly to the YAML header for specific pages (e.g. `analsysis/index.Rmd`), and no luck. I then made a fresh project with `wflow_start()` and tried both of these again, and again no luck. Any idea what I am doing wrong? Here's what `analysis/_site.yml` looks like in the fresh project (i.e. I just changed `cosmo` to `darkly`); the output looks the same as the default when I knit the index.html page (no change to the font, and the background is still white not dark). 

Thanks in advance! My sessionInfo() is below (NB: Catalina...).

```
name: "testing_theme"
output_dir: ../docs
navbar:
  title: "testing_theme"
  left:
  - text: Home
    href: index.html
  - text: About
    href: about.html
  - text: License
    href: license.html
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    theme: darkly
    highlight: textmate
```

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] workflowr_1.6.1      Rcpp_1.0.4.6         ps_1.3.0             rprojroot_1.3-2      digest_0.6.25        later_1.0.0         
 [7] R6_2.4.1             backports_1.1.6      git2r_0.26.1         magrittr_1.5         evaluate_0.14        stringi_1.4.6       
[13] rlang_0.4.5          rstudioapi_0.11      fs_1.4.1             promises_1.1.0       callr_3.4.3          rmarkdown_2.2.0     
[19] tools_3.6.3          stringr_1.4.0        glue_1.4.0           processx_3.4.2       yaml_2.2.1           httpuv_1.5.2        
[25] xfun_0.13            compiler_3.6.3       htmltools_0.4.0.9003 knitr_1.28    
```
