### ISSUE TITLE
wflow_open() not recognising workflowr version in use

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#233]
I opened an existing workflowr (V 1.6.2) project in RStudio and used wflow_open(), as the first command, to create a new analysis notebook. wflow_open() gave a warning message indicating that it thought that the project was using an old workflowr (V < 1).

(I have no idea why I couldn't copy and paste the text below from the console.)

![image](https://user-images.githubusercontent.com/5409051/103621168-e5886580-4f88-11eb-88ed-5bf648ce9869.png)

Session info:

![image](https://user-images.githubusercontent.com/5409051/103621707-b6bebf00-4f89-11eb-8647-2862ae7a806a.png)

![image](https://user-images.githubusercontent.com/5409051/103621804-df46b900-4f89-11eb-8ee0-d0e58e978e4a.png)

Here is the dry-run output of wflow_update():

![image](https://user-images.githubusercontent.com/5409051/103622227-7dd31a00-4f8a-11eb-87d3-99efb506c04e.png)

I wonder whether the warning might be related to my modified _site.yml:

```
name: Frequency-Aware Similarity Calibration
output_dir: ../docs
navbar:
  title: Frequency-Aware Similarity Calibration
  left:
  - text: Home
    href: index.html
  - text: About
    href: about.html
  - text: License
    href: license.html
  right:
  - icon: fa-github
    text: Source code
    href: https://github.com/rgayler/fa_sim_cal
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    toc_depth: 5
    theme: cosmo
    highlight: textmate
    mathjax: "local"
```

Here is my index.Rmd:

```
---
title: "Project Home"
site: workflowr::wflow_site
# output:
#   workflowr::wflow_html:
#     toc: false
output:
  bookdown::html_document2:
    toc: false
editor_options:
  chunk_output_type: console
---

This is the website for the research project "Frequency-Aware Similarity Calibration".

If you have cloned the project to a local computer
this website is rendered in the `docs` subdirectory of the project directory.

If you are using `workflowr` to publish the research website
it will also be rendered online to GitHub Pages.

This page acts as a table of contents for the website.
There are links to the webpages generated from the analysis notebooks
and to the rendered versions of manuscripts/documents/presentations.

---

## [Proposal](proposal.html) {-}  
   This notebook explains the central ideas behind the project.

---

# Analysis Notebooks {-}

## [Get, check and clean data](01_get_check_data.html) {-}  
   Import the raw data, check for anomalies, clean the important attributes, and save the cleaned data for use.


---

# Manuscripts {-}

```
