### ISSUE TITLE
Updating entire website

### ISSUE THREAD

**Issue by jennysjaarda** [workflowr/workflowr#241]
Hello, 

First of all thanks very much for your package - it's a great resource! I have a question about updating the entire site when the `analysis/_site.yml` file is updated, for example. When I use the `dry_run` feature, the result suggests that all `html` files would be rebuilt, but when I attempt it, I get an error that says no files were added. Specifically: 

```
> wflow_publish("analysis/_site.yml", republish = TRUE, dry_run = TRUE)

Summary from wflow_publish

**Step 1: Commit analysis files**

Summary from wflow_git_commit

The following would be attempted:

  $ git add analysis/_site.yml
  $ git commit -m "wflow_publish(\"analysis/_site.yml\", republish = TRUE, dry_run = TRUE)"

**Step 2: Build HTML files**

Summary from wflow_build

Settings:
 republish: TRUE clean_fig_files: TRUE

The following would be built externally each in their own fresh R
session:

docs/about.html
docs/cnv.html
docs/create_custom_cluster_files.html
docs/data_processing_in_genomestudio.html
docs/data_sources.html
docs/extract_genetic_data.html
docs/GWAS_method.html
docs/GWAS_results.html
docs/GWAS_test.html
docs/index.html
docs/info.html
docs/license.html
docs/pheno_quality_control.html
docs/plans.html
docs/setup.html

**Step 3: Commit HTML files**

Summary from wflow_git_commit

The following would be attempted:

  $ git add docs/about.html docs/cnv.html docs/create_custom_cluster_files.html docs/data_processing_in_genomestudio.html docs/data_sources.html docs/extract_genetic_data.html docs/GWAS_method.html docs/GWAS_results.html docs/GWAS_test.html docs/index.html docs/info.html docs/license.html docs/pheno_quality_control.html docs/plans.html docs/setup.html docs/figure/about.Rmd docs/figure/cnv.Rmd docs/figure/create_custom_cluster_files.Rmd docs/figure/data_processing_in_genomestudio.Rmd docs/figure/data_sources.Rmd docs/figure/extract_genetic_data.Rmd docs/figure/GWAS_method.Rmd docs/figure/GWAS_results.Rmd docs/figure/GWAS_test.Rmd docs/figure/index.Rmd docs/figure/info.Rmd docs/figure/license.Rmd docs/figure/pheno_quality_control.Rmd docs/figure/plans.Rmd docs/figure/setup.Rmd docs/site_libs docs/.nojekyll
  $ git commit -m "Build site."
>
> wflow_publish("analysis/_site.yml", republish = TRUE)
Error: Commit failed because no files were added. Attempted to commit the
following files: /data/sgg2/jenny/projects/PSYMETAB/analysis/_site.yml

Any untracked files must manually specified even if `all = TRUE`.

```

Am I missing something obvious? Any thoughts/advice would be appreciated - thanks!

**Comment by stephens999** [comment]
i'm not sure but it looks like it might be failing at the first step. 
can you check that the file `/data/sgg2/jenny/projects/PSYMETAB/analysis/_site.yml`
actually exists in your repo?

**Comment by jennysjaarda** [comment]
Hello, thanks for your response.

The file does indeed exist:

```
master:PSYMETAB$ cat /data/sgg2/jenny/projects/PSYMETAB/analysis/_site.yml
name: PSYMETAB
output_dir: ../docs
navbar:
  title: PSYMETAB
  left:
  - text: Home
    href: index.html
  - text: About
    href: about.html
  - text: Setup
    href: setup.html
  - text: Project
    menu:
    - text: GWAS
      menu:
      - text: "GWAS methods"
        href: GWAS_method.html
      - text: "GWAS results"
        href: GWAS_results.html
  - text: Meetings
    menu:
    - text: "Update 25-09-2020"
      href: Update_meeting_25_09_2020.html
  right:
  - icon: fa-github
    text: Source code
    href: https://github.com/jennysjaarda/PSYMETAB
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    theme: readable
    highlight: textmate
```
