### ISSUE TITLE
Table of content not show on github page but works locally

### ISSUE THREAD

**Issue by liliw-w** [workflowr/workflowr#288]
Hi John,

Thank you for developing and maintaining `workflowr`! It's been really useful with helping me keep track of my project progress for years. 

It all worked perfectly, until year 2023 when I published my page on github, the table of content disappeared -

![image](https://github.com/workflowr/workflowr/assets/55033878/fe8c64bf-5842-4888-a76e-16bdb700ab5d)

Below is the config header I used in `.Rmd` -

```
---
title: "Log2023"
output:
  workflowr::wflow_html:
              toc: true
              toc_depth: 4
editor_options:
  chunk_output_type: console
bibliography: references.bib
---
```

However, TOC works fine in page of older years e.g. 2022, under the exact same header -

![image](https://github.com/workflowr/workflowr/assets/55033878/125394c8-1625-4af6-bb99-f339ff9cb370)

TOC also works fine in the lcoal `html` files not published on github page. I wonder if there is a way to fix TOC to make it appear on github page?

Thank you,
Lili
