### ISSUE TITLE
BibTex references

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#58]
Hi John,

I hope all is well.

I wonder if it is possible to set up BibTex references shared by all pages of a `workflowr` site.

Ideally, I hope that I can only include the path to `bib` file in `index.Rmd` once and use the references in all other `Rmd` files.

It seems that this feature is available in `bookdown`. Below is an example:

```r
--- 
title: "Integrated Enrichment Analysis of Genetic Variants, Biological Pathways and Tissues Across 31 Human Phenotypes"
author: "Xiang Zhu"
date: "`r Sys.Date()`"
knit: bookdown::render_book
output: bookdown::gitbook
documentclass: book
bibliography: [~/Dropbox/rss/Writing/rss_shared/rss.bib]
biblio-style: apalike
link-citations: yes
github-repo: xiangzhu/rss-gsea
---
```
Here is the chapter about `bookdown` BibTex citation: https://bookdown.org/yihui/bookdown/citations.html

**Comment by jdblischak** [comment]
Great question, @xiangzhu. Settings that are shared across all R Markdown documents are specified in `analysis/_site.yml`. Unfortunately they do not allow directly specifying yaml arguments in this document, i.e. you can't just put `bibliography: ~/Dropbox/rss/Writing/rss_shared/rss.bib` directly into this file.

Instead the workaround is to manually specify the arguments to Pandoc which replicate the same behavior. For example, to use the file `analysis/test.bib` in my R Markdown files, I added the following to _site.yml:

```
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: textmate
    include:
      after_body: include/footer.html
    pandoc_args: ["--bibliography", "test.bib",
                  "--filter", "$RSTUDIO_PANDOC/pandoc-citeproc"]
```

The arguments passed to Pandoc tell it which bibliography file to use and to also parse the file with `pandoc-citeproc`. Note that RStudio specifically uses the `pandoc-citeproc` that it comes installed with instead of the Pandoc potentially installed on the system.

Please give this a try and let me know if this is the behavior you want. The main downside is that this makes your code less portable. It requires the use of RStudio. You can add the line `export RSTUDIO_PANDOC=/usr/lib/rstudio/bin/pandoc` to your .bashrc file on Linux to enable you to also build the pages from the R console. Thus you may want to make a note in your README that some configuration is required if others want to run your code.
